language: python
python:
  - 2.7
  - 3.3
    dist:trusty
  - 3.4
  - 3.5
  - pypy
  - pypy3
install:
  - pip install -e ".[test]"
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then
        py.test --doctest-modules --doctest-glob="*.rst" --ignore setup.py;
    else
        isort --recursive --diff intervals tests && isort --recursive --check-only intervals tests
        flake8 intervals tests
        py.test;
    fi
